### ISSUE TITLE
สามารถดึงโค้ด LAC จากตัวโมเด็มได้ไหม

### ISSUE THREAD

**Issue by suriya1977** [trueiot/True-NB-IoT-Board#16]
ผมอยากจะรู้ว่า มีวิธีดึงโค้ด LAC (location area code) จากตัวโมเด็มได้ไหมครับ ทำอย่างไรดีครับ

**Comment by chalitcha** [comment]
LAC ในระบบ 3G เป็นตัวบอกสถานีฐาน  ในขณะที่ระบบ 4G (LTE) จะเรียก TAC (Tracking area code)
NB-IoT เป็นเทคโนโลยีนึงของ LTE ครับ ฉะนั้นเราอ่านค่าจาก TAC ก็ได้เหมือนกัน

ลองดูคำสั่ง AT+CEREG ดูครับ

**Comment by suriya1977** [comment]
ขอบคุณครับ สำหรับคำอธิบาย

ผมได้ผลจากการเรียก "AT+CEREG=4" และถัดไปก็เรียก "AT+CEREG?" ครับ :-)
