### ISSUE TITLE
ตัว json format ที่ส่งให้ thingsboard สามารถปรับตัวแปรให้เป็น float ได้ไหมครับ

### ISSUE THREAD

**Issue by armyjam** [trueiot/True-NB-IoT-Board#19]
พอดีลองปรับชนิดตัวแปรจาก int เป็น float แล้วปรากฏว่าตัว thingsboard ไม่สามารถรับค่าได้ครับ

**Comment by suriya1977** [comment]
คุณลองดูวิธีนี้ก็ได้ อาจจะใช้ได้ครับ

char jsonData[] = "{\"temperature\":%s, \"humidity\":%s }\0";
char buff[48];
.
.
.
String temp = String(random(10,20) / 10.0);
String rh = String(random(50,60) / 10.0);
.
.
.
sprintf(buff, jsonData,  temp.c_str(), rh.c_str());

**Comment by armyjam** [comment]
เดี๋ยวลองดูนะครับ ขอบคุณครับ

**Comment by armyjam** [comment]
> คุณลองดูวิธีนี้ก็ได้ อาจจะใช้ได้ครับ
> 
> char jsonData[] = "{"temperature":%s, "humidity":%s }\0";
> char buff[48];
> .
> .
> .
> String temp = String(random(100,200) / 10.0);
> String rh = String(random(500,600) / 10.0);
> .
> .
> .
> sprintf(buff, jsonData, temp.c_str(), rh.c_str());

ตอนนี้ลองแล้ว ใช้ได้ครับ ขอบคุณมากๆครับ

**Comment by suriya1977** [comment]
> ตอนนี้ลองแล้ว ใช้ได้ครับ ขอบคุณมากๆครับ

ยินดีด้วยครับ :-)

**Comment by prayutcheewan** [comment]
การกำหนด String temp = String(random(100,200) / 10.0);
                 String rh = String(random(500,600) / 10.0);
ตัวเลข random(100,200)/10.0  หมายถึงอะไรครับ (ผมมเพิ่งฝึดหัดเขียนโปรแกรมนะครับ)
แล้วก็พบปัญหาการส่งค่าทศนิยมขึ้น Thingsboard เช่นกันครับ
พอดีผมจะลองนำคำแนะนำนี้ไปใช้ดูนะครับ
เบื้องต้นผมลอง compliance ดูแล้ว ปรากฏว่าตัวเลขมันเพี้ยนๆ หน่อยนะครับ

**Comment by armyjam** [comment]
random(100,200) เป็นการสุ่มตัวเลขที่อยู่ในช่วง 100-200 ขึ้นมา 1 ตัว แล้ว /10.0 คือการหารด้วย 10 และมีทศนิยม 1 ตำแหน่งครับ

**Comment by prayutcheewan** [comment]
ขอบพระคุณอย่างสูงครับ

**Comment by prayutcheewan** [comment]
ขอบพระคุณอย่างสูงครับ
    On Wednesday, 17 April 2019, 4:59:03 pm GMT+7, S. Koedkaen <notifications@github.com> wrote:  
 
 
random(100,200) เป็นการสุ่มตัวเลขที่อยู่ในช่วง 100-200 ขึ้นมา 1 ตัว แล้ว /10.0 คือการหารด้วย 10 และมีทศนิยม 1 ตำแหน่งครับ
