### ISSUE TITLE
ใช้ Qnavigator ทดสอบ board ,Register network fail ขึ้น fail to to activate context profile.

### ISSUE THREAD

**Issue by directjhoffcxiv** [trueiot/True-NB-IoT-Board#8]
ผมทดสอบบอร์ดตามคู่มือ ด้วย Qnavigator 
Register network fail ขึ้น fail to to activate context profile.
location ที่ผมอยู่มีสัญญาณโทรศัพท์ true นะครับ.
รบกวนขอคำแนะนำแนวทางแก้ไขหน่อยนะครับ

**Comment by directjhoffcxiv** [comment]
ภาพ error และ _Log ![error1](https://user-images.githubusercontent.com/28134885/41833792-fc0446ee-787b-11e8-84bc-8c2e47029de8.png)
[log132856.txt](https://github.com/trueiot/True-NB-IoT-Board/files/2131966/log132856.txt)

**Comment by trueiot** [comment]
อำเภอหางดง La , Long 18.856840, 99.059066  พื้นที่ตามที่แจ้ง อยู่ภายใต้ coverage  CMI1517P_9NB01 ให้บริการ สำหรับ NB-IoT ครับ

**Comment by directjhoffcxiv** [comment]
La, Long ที่ส่งไปให้นั้นที่ อ.สันทรายครับ(สถานที่ใช้งานจริง) สถานที่ที่ทดสอบแล้วไม่ได้ network คือ ที่ หางดงครับ(สถานที่ทดสอบ) ยังไงรกวนส่งสินค้ากลับมาเพื่อทดสอบให้หน่อยนะครับ

**Comment by trueiot** [comment]
งั้นรบกวนส่ง lat/Long ของ หางดงมาอีกที่ได้มั้ยครับ เดี๋ยวส่งอุปกรณ์กลับให้ครับ

**Comment by directjhoffcxiv** [comment]
18°42'12.1"N 98°54'33.0"E ครับ
